FinalProject/src/company/config/routes.rb
Rails.application.routes.draw do
	

  get "sessions/new"
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "students#new", :as => "sign_up"
  root :to => "sessions#new"
   resources :students do
      resources :verifications
      resources :reviews
      member do
      get 'verify', :action => 'verify'
      get 'upload', :action => 'upload'
      end
    end

  get "students/:id/show_student_iaf" => "students#show_student_iaf", :as => "student_iafs"
  get "students/:id/show_iafs" => "students#show_iafs", :as => "student_all_iafs"
  get "students/:id/sign_iaf" => "students#sign_iaf", :as => "sign_iaf"
  get "students/:id/unsign_iaf" => "students#unsign_iaf", :as => "unsign_iaf"
  get "company_informations/:company_information_id/iafs/:id/shortlist" => "iafs#shortlist", :as => "shortlist"
  get "company_informations/:company_information_id/iafs/:id/select_student" => "iafs#select_student", :as => "select_student"
  get "company_informations/:company_information_id/iafs/:id/unselect_student" => "iafs#unselect_student", :as => "unselect_student"
  get "students/:id/verify_confirm" => "students#verify_confirm", :as => "confirm_student"
  get "company_informations/:company_information_id/iafs/:id/freeze_shortlist" => "iafs#freeze_shortlist", :as => "freeze_shortlist"
 
resources :sessions
  resources :company_informations	do
  	resources :iafs
  end
end

FinalProject/src/company/app/models/company_information.rb
class CompanyInformation < ApplicationRecord
	has_many :iafs
end

FinalProject/src/company/app/controllers/company_informations_controller.rb
class CompanyInformationsController < ApplicationController
  before_action :set_company_information, only: [:show, :edit, :update, :destroy]

  # GET /company_informations
  # GET /company_informations.json
  def index
    @company_informations = CompanyInformation.all
  end

  # GET /company_informations/1
  # GET /company_informations/1.json
  def show
  end

  # GET /company_informations/new
  def new
    @company_information = CompanyInformation.new
  end

  # GET /company_informations/1/edit
  def edit
  end

  # POST /company_informations
  # POST /company_informations.json
  def create
    @company_information = CompanyInformation.new(company_information_params)

    respond_to do |format|
      if @company_information.save
        format.html { redirect_to @company_information, notice: 'Company information was successfully created.' }
        format.json { render :show, status: :created, location: @company_information }
      else
        format.html { render :new }
        format.json { render json: @company_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_informations/1
  # PATCH/PUT /company_informations/1.json
  def update
    respond_to do |format|
      if @company_information.update(company_information_params)
        format.html { redirect_to @company_information, notice: 'Company information was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_information }
      else
        format.html { render :edit }
        format.json { render json: @company_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_informations/1
  # DELETE /company_informations/1.json
  def destroy
    @company_information.destroy
    respond_to do |format|
      format.html { redirect_to company_informations_url, notice: 'Company information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_information
      @company_information = CompanyInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_information_params
      params.require(:company_information).permit(:name, :address_line1, :address_line2, :city, :country, :pin, :url, :contact_person, :designation, :email, :contact_number, :cell_number, :nature)
    end
end

FinalProject/src/company/app/helpers/company_informations_helper.rb
module CompanyInformationsHelper
end

FinalProject/src/company/app/views/company_informations/_form.html.erb
<%= form_for(company_information) do |f| %>
  <% if company_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_information.errors.count, "error") %> prohibited this company_information from being saved:</h2>

      <ul>
      <% company_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  

  

  

  

 
  

 
  

  

  
  


 


  

 
  


  


  




    <!-- <form class="row"> -->
      <div class="col-xs-7">
        <div class="field form-group input-group">
          <%= f.label :name, "Company Name <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="col-xs-5">
        <div class="form-group input-group">
          <div class="input-group-addon">Nature</div>
          <select class="form-control" name="company_information[nature]">
            <option value="NA">No category</option>
            <option value="analytics">analytics</option>
            <option value="consulting">consulting</option>
            <option value="core">core</option>
            <option value="engg">engg</option>
            <option value="finance">finance</option>
            <option value="FMCG">FMCG</option>
            <option value="IT">IT</option>
            <option value="others">others</option>
            <option value="public">public</option>
            <option value="r&d">r&d</option>
            <option value="services">services</option>
            <option value="software">software</option>
            <option value="tech">tech</option>
          </select>
        </div>
      </div>
      <div class="divider col-xs-12"></div>
      <div class="col-xs-7">
         <div class="field form-group input-group">
            <%= f.label :contact_person, "Contact Person <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
            <%= f.text_field :contact_person, class: 'form-control' %>
          </div>
        <div class="field form-group input-group">
          <%= f.label :designation, "Designation <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :designation, class: 'form-control' %>
        </div>
        <div class="field form-group input-group">
          <%= f.label :email, "Email <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="col-xs-5">
        <div class="field form-group input-group">
          <%= f.label :contact_number, "Contact Number <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :contact_number, class: 'form-control' %>
        </div>
         <div class="field form-group input-group">
          <%= f.label :cell_number, "Cell Number <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :cell_number, class: 'form-control' %>
        </div>
        <div class="form-group input-group">
          <div class="input-group-addon">Fax No.</div>
          <input type="text" class="form-control" name="name">
        </div>
      </div>
      <div class="divider col-xs-12"></div>
      <div class="col-xs-6">
        <div class="field form-group input-group">
          <%= f.label :address_line1, "Address line 1 <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :address_line1, class: 'form-control' %>
        </div>
        <div class="field form-group input-group">
          <%= f.label :address_line2, "Address line 2 <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :address_line2, class: 'form-control' %>
        </div>
        <div class="field form-group input-group">
          <%= f.label :city, "City <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :city, class: 'form-control' %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="field form-group input-group">
          <%= f.label :country, "Country <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :country, class: 'form-control' %>
        </div>
        <div class="field form-group input-group">
          <%= f.label :pin, "Pin <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :pin, class: 'form-control' %>
        </div>
        <div class="field form-group input-group">
          <%= f.label :url, "url <strong style='color:red;'>*</strong>".html_safe, class: 'input-group-addon' %>
          <%= f.text_field :url, class: 'form-control' %>
        </div>
      </div>
      <!-- <div class="col-xs-12">
        <input type="submit" name="edit" value="Register" class="btn btn-danger float-R">
        <input type="reset" name="reset" value="Reset" class="btn btn-primary">
      </div> -->
    <!-- </form> -->
<!-- <div class="col-md-offset-4 col-md-2"> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<!-- </div> -->
<% end %>

FinalProject/src/company/app/views/company_informations/edit.html.erb
  <div id="menu">
    <ul>
      <li class="current_page_item"><a href="#">Profile</a></li>
      <li><%= link_to 'IAFS', company_information_iafs_path(@company_information) %> </li>
      <li class="last"><%= link_to "All Companies", company_informations_path %></li>
    </ul>
  </div>
  <div id="welcome">


<%= render 'form', company_information: @company_information %>

<div class="col-md-offset-3 col-md-3">
<%= link_to 'IAFS', company_information_iafs_path(@company_information), class: "btn btn-primary" %> 
</div>

<div class="col-md-offset-2 col-md-2">
<%= link_to 'Back', company_informations_path, class: "btn btn-danger"  %>
</div>
<br><br>
  </div>
  

FinalProject/src/company/app/views/company_informations/index.html.erb
<div id="menu">
    <ul>
      <li class="last"><a href="#">All Companies</a></li>
    </ul>
  </div>
<div id="welcome">

<p id="notice"><%= notice %></p>

<h1>Company Informations</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Url</th>
      <th>Contact person</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_informations.each do |company_information| %>
      <tr>
        <td><%= company_information.name %></td>
        <td><%= company_information.city %></td>
        <td><%= company_information.url %></td>
        <td><%= company_information.contact_person %></td>
        <td><%= company_information.nature %></td>
        <!-- <td><%#= link_to 'Show', company_information %></td> -->
        <td><%= link_to 'Show', edit_company_information_path(company_information) %></td>
        <td><%= link_to 'Destroy', company_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Information', new_company_information_path %>
<%= link_to 'Login Page', root_path, class: "btn btn-primary btn-sm float-R" %>
</div>

FinalProject/src/company/app/views/company_informations/new.html.erb
<h2>New Company Information</h2>
<br />

<%= render 'form', company_information: @company_information %>

<%= link_to 'Back', company_informations_path %>

FinalProject/src/company/app/views/company_informations/show.html.erb
<div id="welcome">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_information.name %>
</p>

<p>
  <strong>Address line1:</strong>
  <%= @company_information.address_line1 %>
</p>

<p>
  <strong>Address line2:</strong>
  <%= @company_information.address_line2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @company_information.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company_information.country %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @company_information.pin %>
</p>

<p>
  <strong>Url:</strong>
  <%= @company_information.url %>
</p>

<p>
  <strong>Contact person:</strong>
  <%= @company_information.contact_person %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @company_information.designation %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company_information.email %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @company_information.contact_number %>
</p>

<p>
  <strong>Cell number:</strong>
  <%= @company_information.cell_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @company_information.nature %>
</p>

<%= link_to 'IAFS', company_information_iafs_path(@company_information) %> |
<%= link_to 'Edit', edit_company_information_path(@company_information) %> |
<%= link_to 'Back', company_informations_path %>

</div>