FinalProject/src/company/config/routes.rb
Rails.application.routes.draw do
	

  get "sessions/new"
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "students#new", :as => "sign_up"
  root :to => "sessions#new"
   resources :students do
      resources :verifications
      resources :reviews
      member do
      get 'verify', :action => 'verify'
      get 'upload', :action => 'upload'
      end
    end

  get "students/:id/show_student_iaf" => "students#show_student_iaf", :as => "student_iafs"
  get "students/:id/show_iafs" => "students#show_iafs", :as => "student_all_iafs"
  get "students/:id/sign_iaf" => "students#sign_iaf", :as => "sign_iaf"
  get "students/:id/unsign_iaf" => "students#unsign_iaf", :as => "unsign_iaf"
  get "company_informations/:company_information_id/iafs/:id/shortlist" => "iafs#shortlist", :as => "shortlist"
  get "company_informations/:company_information_id/iafs/:id/select_student" => "iafs#select_student", :as => "select_student"
  get "company_informations/:company_information_id/iafs/:id/unselect_student" => "iafs#unselect_student", :as => "unselect_student"
  get "students/:id/verify_confirm" => "students#verify_confirm", :as => "confirm_student"
  get "company_informations/:company_information_id/iafs/:id/freeze_shortlist" => "iafs#freeze_shortlist", :as => "freeze_shortlist"
 
resources :sessions
  resources :company_informations	do
  	resources :iafs
  end
end

FinalProject/src/company/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
		@student = Student.find(params[:student_id])
		@reviews=Review.all
	end	

	def show
    	@review = review.find(params[:id])
  	end

	def new
		 @student = Student.find(params[:student_id])
		 @review = @student.reviews.build
	end

  	def create
  		@student = Student.find(params[:student_id])
  		@review = @student.reviews.build(review_params)

  	
    if @review.save
      flash[:success] = "The review was added!"
      redirect_to student_reviews_path
    else
      render 'new'
    end
 	end

 	def destroy
    @review = Review.find(params[:id])
    @review.destroy
 
    redirect_to student_reviews_path
  end

 	 private

 	 def review_params
    	params.require(:review).permit(:organization, :review, :student_id)
  	 end
end

FinalProject/src/company/app/helpers/reviews_helper.rb
module ReviewsHelper
end

FinalProject/src/company/app/views/reviews/index.html.erb
  <div id="menu">
    <ul>
      <li><%= link_to "Home", student_path(@student.id) %></li>
      <li><%= link_to "IAFS", student_all_iafs_path(@student.id) %></li>
      <li><%= link_to "Resumes", student_verifications_path(@student.id) %></li>
      <li><%= link_to "Profile", edit_student_path(@student.id) %></li>
      <li class="current_page_item"><a href="#">Reviews</a></li>
      <li class="last"><%= link_to "Logout", log_out_path %></li>
    </ul>
  </div>
  <div id="two-columns">
    <div id="column-list">
      <h2>Resume</h2>
      <ul class="list-style2">
        <li class="first"><%= link_to "One page technical (Resume_1)", @student.cv.url(:original, false) %></li><!-- 
        <li><%= link_to "Two page technical (Resume_1)", @student.cv.url(:original, false) %></li>
        <li><%= link_to "Three page technical (Resume_1)", @student.cv.url(:original, false) %></li>
        <li><%= link_to "One page non-technical (Resume_1)", @student.cv.url(:original, false) %></li>
        <li><%= link_to "Two page non-technical (Resume_1)", @student.cv.url(:original, false) %></li> -->
      </ul>
      <!-- <h2>SOP</h2>
      <ul class="list-style2 text-center">
        <li class="first"><%= link_to "SOP 1", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 2", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 3", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 4", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 5", @student.cv.url(:original, false) %></li>
      </ul> -->
    </div>
    <div id="column-details">
      <!-- For Student Side -->
      <h2>Past Reviews</h2>
      <ul class="list-style1">
        <% @reviews.each do |review| %>
        <li class="bottom row">
          <div class="col-xs-9">
            <h4><%= review.organisation %></h4>
            <p><strong><%= review.review %></strong>
            <% if current_student.admin %>
            <%= link_to 'Remove Review', student_review_path(:id =>review), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger float-R' %>
            <% end %>
          </div>
        </li>
        <% end %>
        
        <!-- <li class="bottom row">
          <div class="col-xs-9">
            <h4>Short listed for KVPY Fellowship Award conducted by IISC, Bangalore</h4>
            <p><strong>File for Proof : </strong><a href="#">someOtherFile.jpg</a></p>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-success">Validated</button></div>
        </li>
        <li class="bottom row">
          <div class="col-xs-9">
            <h4>Secured 98/100 in the finals of All India Open Mathematics Scholarship Examination (AIOMSE) conducted by Institute for Promotion of Mathematics (IPM)</h4>
            <p><strong>File for Proof : </strong><a href="#">someAnotherFile.jpg</a><button class="btn btn-info btn-sm margin-left-5">Edit</button></p>
            <button class="btn btn-danger">Remove Point</button>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-danger">Invalidated</button><br><strong>Comment : </strong>Proof shows 99/100, Please update the point</div>
        </li> -->
        <li class="row">
          <h2><%= link_to 'Add a Review', new_student_review_path, class: "btn btn-primary btn-lg margin-left-5" %></h2>
        </li>
      </ul>
      <!-- End For Student Side -->
      <!-- For Verifier Side -->
      <!-- <h2>Resume_0 <a href="#" class="float-R">140050007-0.pdf</a></h2>
      <ul class="list-style1">
        <li class="first row">
          <div class="col-xs-9">
            <h4>City Topper in SSC Maharashtra Secondary State Board Examination</h4>
            <p><strong>File for Proof : </strong><a href="#">someFile.jpg</a></p>
            <div class="btn-group float-R" role="group" aria-label="..."><button class="btn btn-success">Validate</button><button class="btn btn-danger">Invalidate</button></div>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-secondary">Pending</button></div>
        </li>
        <li class="row">
          <div class="col-xs-9">
            <h4>Short listed for KVPY Fellowship Award conducted by IISC, Bangalore</h4>
            <p><strong>File for Proof : </strong><a href="#">someOtherFile.jpg</a></p>
            <div class="btn-group float-R" role="group" aria-label="..."><button class="btn btn-success">Validate</button><button class="btn btn-danger">Invalidate</button></div>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-success">Validated</button></div>
        </li>
        <li class="row">
          <div class="col-xs-9">
            <h4>Secured 98/100 in the finals of All India Open Mathematics Scholarship Examination (AIOMSE) conducted by Institute for Promotion of Mathematics (IPM)</h4>
            <p><strong>File for Proof : </strong><a href="#">someAnotherFile.jpg</a></p>
            <div class="btn-group float-R" role="group" aria-label="..."><button class="btn btn-success">Validate</button><button class="btn btn-danger">Invalidate</button></div>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-danger">Invalidated</button><br><strong>Comment : </strong>Proof shows 99/100, Please update the point</div>
        </li>
      </ul>
       -->
    </div>
  </div>

FinalProject/src/company/app/views/reviews/new.html.erb
<%= form_for :review, url: student_reviews_path do |f| %>
  <p>
    <%= f.label :organisation %><br>
    <%= f.text_field :organisation %>
  </p>

  <p>
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

FinalProject/src/company/app/views/reviews/show.html.erb
<p>
  
    <tr>
     <td><%= @verification.student_id %> </td>	
      <td><%= @verification.point %></td>
      <td> student_id</td>
      <td><%= @verification.student_id %></td>
      <td><%= link_to "Download", @verification.proof.url(:original, false) %></td>
      <td><%= @verification.mail_id %></td>
    </tr>
 </p>   

<p><%= link_to 'Add another', new_student_verification_path %> </p>
<p><%= link_to 'Back', student_verifications_path %>  </p>  