FinalProject/src/company/config/routes.rb
Rails.application.routes.draw do
	

  get "sessions/new"
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "students#new", :as => "sign_up"
  root :to => "sessions#new"
   resources :students do
      resources :verifications
      resources :reviews
      member do
      get 'verify', :action => 'verify'
      get 'upload', :action => 'upload'
      end
    end

  get "students/:id/show_student_iaf" => "students#show_student_iaf", :as => "student_iafs"
  get "students/:id/show_iafs" => "students#show_iafs", :as => "student_all_iafs"
  get "students/:id/sign_iaf" => "students#sign_iaf", :as => "sign_iaf"
  get "students/:id/unsign_iaf" => "students#unsign_iaf", :as => "unsign_iaf"
  get "company_informations/:company_information_id/iafs/:id/shortlist" => "iafs#shortlist", :as => "shortlist"
  get "company_informations/:company_information_id/iafs/:id/select_student" => "iafs#select_student", :as => "select_student"
  get "company_informations/:company_information_id/iafs/:id/unselect_student" => "iafs#unselect_student", :as => "unselect_student"
  get "students/:id/verify_confirm" => "students#verify_confirm", :as => "confirm_student"
  get "company_informations/:company_information_id/iafs/:id/freeze_shortlist" => "iafs#freeze_shortlist", :as => "freeze_shortlist"
 
resources :sessions
  resources :company_informations	do
  	resources :iafs
  end
end

FinalProject/src/company/app/models/iaf.rb
class Iaf < ApplicationRecord
	belongs_to :company_information
	has_many :shortlists
	validates :profile, presence:true
	validates :intern_job_description, presence: true
	validates :stipend, presence: true
	validates :opens_on, presence: true
	validates :closes_on, presence: true
	validates :departments, presence: true
	validates :place_of_posting, presence: true
end

FinalProject/src/company/app/controllers/iafs_controller.rb
class IafsController < ApplicationController

	def index
		@company_information = CompanyInformation.find(params[:company_information_id])
		@iaf = @company_information.iafs.all
	end
	def new
		@company_information = CompanyInformation.find(params[:company_information_id])
		@iaf = @company_information.iafs.build
	end

	def create
		@company_information = CompanyInformation.find(params[:company_information_id])
		@iaf = @company_information.iafs.build(iaf_params)
		if @iaf.save
		redirect_to company_information_iaf_path(:id => @iaf)
		else
			render 'new'
		end
	end

	def select_student
	    num = JSON.parse ActiveRecord::Base.connection.execute("SELECT count(*) FROM shortlists where (iaf_id = "+params[:iaf]+" and student_id  = "+params[:student]+" and status = 0);").to_json;
	     # = num;
	    if (num[0][0] == 1)
	      ActiveRecord::Base.connection.execute("UPDATE shortlists SET status = 1 WHERE (iaf_id = "+params[:iaf]+" and student_id  = "+params[:student]+");");
	    end
		redirect_to shortlist_path(:id => params[:iaf])
	end

  	def unselect_student
	    num = JSON.parse ActiveRecord::Base.connection.execute("SELECT count(*) FROM shortlists where (iaf_id = "+params[:iaf]+" and student_id  = "+params[:student]+" and status = 1);").to_json;
	    if (num[0][0] == 1)
	      ActiveRecord::Base.connection.execute("UPDATE shortlists SET status = 0 WHERE (iaf_id = "+params[:iaf]+" and student_id  = "+params[:student]+");");
	    end
		redirect_to shortlist_path(:id => params[:iaf])
	end
	
	def freeze_shortlist
		ActiveRecord::Base.connection.execute("UPDATE iafs SET status = 2 WHERE (id = "+params[:iaf]+");");

		ActiveRecord::Base.connection.execute("DELETE FROM shortlists WHERE (iaf_id = "+params[:iaf]+" and status = 0);");
		ActiveRecord::Base.connection.execute("UPDATE shortlists SET status = 2 WHERE (iaf_id = "+params[:iaf]+" and status = 1);");

		ActiveRecord::Base.connection.execute("CREATE TEMPORARY TABLE tempTable (iaf_id int, student_id int, status int);");
		ActiveRecord::Base.connection.execute("INSERT INTO tempTable (SELECT iaf_id, student_id, status FROM shortlists);");
		ActiveRecord::Base.connection.execute("delete from shortlists where exists (select * from tempTable where tempTable.status=2 and shortlists.student_id=tempTable.student_id and (not shortlists.status = 2));");
		ActiveRecord::Base.connection.execute("DROP TABLE tempTable;");

		redirect_to shortlist_path(:id => params[:iaf])
	end

	def show
		@company_information = CompanyInformation.find(params[:company_information_id])
		@iaf = @company_information.iafs.find(params[:id])
	end
	def shortlist
		@list = ActiveRecord::Base.connection.execute("SELECT * FROM shortlists, students WHERE (iaf_id = "+params[:id]+") AND (shortlists.student_id = students.id);");
	end 
	def edit
		@company_information = CompanyInformation.find(params[:company_information_id])
		@iaf = @company_information.iafs.find(params[:id])
	end
	def update
		@iaf = Iaf.find(params[:id])
		if @iaf.update(iaf_params)
			redirect_to company_information_iaf_path(:id => @iaf)
		else
			render 'edit'
		end

	end
	def destroy
  		@iaf = Iaf.find(params[:id])
  		@iaf.destroy
 
  		redirect_to company_information_iafs_path
	end
	private
		def iaf_params
			params.require(:iaf).permit(:profile, :intern_job_description, :place_of_posting, :stipend, :opens_on, :closes_on, :cpi_cutoff, :departments, :cse, :elec, :mech, :meta)
		end
	
end

FinalProject/src/company/app/helpers/iafs_helper.rb
module IafsHelper
end

FinalProject/src/company/app/views/iafs/edit.html.erb
<div id="welcome">
<h1>Editing IAF </h1>
<%= form_for :iaf,url: company_information_iaf_path(@company_information,@iaf), method: :patch, :html => {class: 'row'} do |f| %>
<% if @iaf.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@iaf.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @iaf.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
        <div class="col-xs-12">
          <div class="form-group input-group">
            <div class="input-group-addon">Profile<span style="color:red;">*</span></div>
            <input type="text" class="form-control" name="iaf[profile]" required="required" value="<%= @iaf.profile %>">
          </div>
        </div>
        <div class="col-xs-12">
          <div class="form-group">
            <%= f.label :intern_job_description %><br>
            <%= f.text_area :intern_job_description, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group input-group">
            <div class="input-group-addon">Place of Posting</div>
            <input type="text" class="form-control" name="iaf[place_of_posting]" value="<%= @iaf.place_of_posting %>">
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">Stipend</div>
            <input type="number" class="form-control" name="iaf[stipend]" value="<%= @iaf.stipend %>">
            <div class="input-group-addon">INR</div>
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">CPI Cut-off</div>
            <input type="number" step="0.01" class="form-control" name="iaf[cpi_cutoff]" value="<%= @iaf.cpi_cutoff %>">
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group input-group">
            <div class="input-group-addon">Opens On</div>
            <input type="date" class="form-control" name="iaf[opens_on]" value="<%= @iaf.opens_on %>">
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">Closes On</div>
            <input type="date" class="form-control" name="iaf[closes_on]" value="<%= @iaf.closes_on %>">
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">CSE</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[cse]" value="<%= @iaf.cse %>" aria-label="..."></span>
            <div class="input-group-addon">ELEC</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[elec]" value="<%= @iaf.elec %>" aria-label="..."></span>
            <div class="input-group-addon">META</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[meta]" value="<%= @iaf.meta %>" aria-label="..."></span>
            <div class="input-group-addon">MECH</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[mech]" value="<%= @iaf.mech %>" aria-label="..."></span>
          </div>
        </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', company_information_iafs_path%>
</div>

FinalProject/src/company/app/views/iafs/index.html.erb
<div id="menu">
    <ul>
      <li><%= link_to "Profile", edit_company_information_path(@company_information) %></li>
      <li class="current_page_item"><a href="#">IAFS</a></li>
      <li class="last"><%= link_to "All Companies", company_informations_path %></li>
    </ul>
  </div>
<div id="welcome">

<h1>IAF's filled so far </h1>
<br>
<table class="table table-striped">

<% @iaf.each do |iaf| %>
<tr>
<td><%= iaf.profile %> </td>
<td><%= link_to 'Shortlist', shortlist_path(params[:company_information_id],iaf)%> </td>
<td><%=link_to 'Edit IAF',edit_company_information_iaf_path(params[:company_information_id],iaf)%></td>
<td><%=link_to 'Remove IAF',company_information_iaf_path(params[:company_information_id],iaf), method: :delete, data: {confirm: 'Do you really want to remove the IAF? Once deleted, IAF can\'t be recovered'}%></td>
</tr>
<% end %>
</table>

<%= link_to 'New IAF', new_company_information_iaf_path %>

</div>

FinalProject/src/company/app/views/iafs/new.html.erb
<div id="welcome">
<%= form_for :iaf,url: company_information_iafs_path, :html => {class: 'row'} do |f| %>
<% if @iaf.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@iaf.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @iaf.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
<div class="col-xs-12">
          <div class="form-group input-group">
            <div class="input-group-addon">Profile<span style="color:red;">*</span></div>
            <input type="text" class="form-control" name="iaf[profile]" required="required" value="<%= @iaf.profile %>">
          </div>
        </div>
        <div class="col-xs-12">
          <div class="form-group">
            <%= f.label :intern_job_description %><br>
            <%= f.text_area :intern_job_description, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group input-group">
            <div class="input-group-addon">Place of Posting</div>
            <input type="text" class="form-control" name="iaf[place_of_posting]" value="<%= @iaf.place_of_posting %>">
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">Stipend</div>
            <input type="number" class="form-control" name="iaf[stipend]" value="<%= @iaf.stipend %>">
            <div class="input-group-addon">INR</div>
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">CPI Cut-off</div>
            <input type="number" step="0.01" class="form-control" name="iaf[cpi_cutoff]" value="<%= @iaf.cpi_cutoff %>">
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group input-group">
            <div class="input-group-addon">Opens On</div>
            <input type="date" class="form-control" name="iaf[opens_on]" value="<%= @iaf.opens_on %>">
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">Closes On</div>
            <input type="date" class="form-control" name="iaf[closes_on]" value="<%= @iaf.closes_on %>">
          </div>
          <div class="form-group input-group">
            <div class="input-group-addon">CSE</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[cse]" value="<%= @iaf.cse %>" aria-label="..."></span>
            <div class="input-group-addon">ELEC</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[elec]" value="<%= @iaf.elec %>" aria-label="..."></span>
            <div class="input-group-addon">META</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[meta]" value="<%= @iaf.meta %>" aria-label="..."></span>
            <div class="input-group-addon">MECH</div>
            <span class="input-group-addon"><input type="checkbox" name="iaf[mech]" value="<%= @iaf.mech %>" aria-label="..."></span>
          </div>
        </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', company_information_iafs_path%>
</div>  

FinalProject/src/company/app/views/iafs/shortlist.html.erb
<div id="welcome">
<h1>Listing signed students</h1>
 <br>
<!-- <h2><%= debug @list %></h2>  -->
<table class="table table-striped">
  <tr>
    <th>name</th>
    <th>roll no</th>
    <th>department</th>
    <th colspan="1"></th>
  </tr>
 
  <% @list.each(:as => :hash) do |student| %>
    <tr>
      <td><%= student['name'] %></td>
      <td><%= student['roll_no'] %></td>
      <td><%= student['department'] %></td>
      <!-- <td><%# link_to "Resume", student.cv.url(:original, false) %></td> -->
        <% temp = JSON.parse ActiveRecord::Base.connection.execute("SELECT count(*) FROM shortlists where (iaf_id = "+params[:id].to_s+" and student_id = "+student['id'].to_s+" and status > 0);").to_json; %>
        <% total = temp[0][0] %>
        <% if total > 0 %>
        <td><%= link_to('Shortlisted',{:action => 'unselect_student',:student => student['id'], :iaf => params[:id]},{class: "btn btn-success"}) %></td>
        <% else %>
        <td><%= link_to('Shortlist',{:action => 'select_student',:student => student['id'], :iaf => params[:id]}, {class: "btn btn-primary"}) %></td>
        <% end %>
    </tr>
  <% end %>
</table>
<div class="col-md-offset-3 col-md-3">
  <%= link_to('Freeze ShortList',{:action => 'freeze_shortlist',:iaf => params[:id]},{ class: "btn btn-danger"}) %>
</div>

<div class="col-md-offset-2 col-md-2">
  <%= link_to 'Back', company_information_iafs_path, class: "btn btn-primary"%>
</div>
<br><br>

</div>

FinalProject/src/company/app/views/iafs/show.html.erb
<p>
<strong>Job Profile:</strong>
  <%= @iaf.profile %>
</p>
 
<p>
  <strong>Internship Job Description:</strong>
  <%= @iaf.intern_job_description %>
</p>

<p>
  <strong>Place of Posting:</strong>
  <%= @iaf.place_of_posting %>
</p>
 
<p>
  <strong>Stipend:</strong>
  <%= @iaf.stipend %>
</p>

<p>
  <strong>Opens On:</strong>
  <%= @iaf.opens_on %>
</p>
 
<p>
  <strong>Closes On:</strong>
  <%= @iaf.closes_on %>
</p>

<p>
  <strong>CPI Cutoff:</strong>
  <%= @iaf.cpi_cutoff %>
</p>
 
<p>
  <strong>Open for departments:</strong>
  <%= @iaf.departments %>
</p>

<%=link_to 'Edit IAF', edit_company_information_iaf_path(@company_information,@iaf)%>
<%= link_to 'Show Signed Students', shortlist_path(@company_information,@iaf)%>
<%= link_to 'Back', company_information_iafs_path%>