FinalProject/src/company/config/routes.rb
Rails.application.routes.draw do
	

  get "sessions/new"
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "students#new", :as => "sign_up"
  root :to => "sessions#new"
   resources :students do
      resources :verifications
      resources :reviews
      member do
      get 'verify', :action => 'verify'
      get 'upload', :action => 'upload'
      end
    end

  get "students/:id/show_student_iaf" => "students#show_student_iaf", :as => "student_iafs"
  get "students/:id/show_iafs" => "students#show_iafs", :as => "student_all_iafs"
  get "students/:id/sign_iaf" => "students#sign_iaf", :as => "sign_iaf"
  get "students/:id/unsign_iaf" => "students#unsign_iaf", :as => "unsign_iaf"
  get "company_informations/:company_information_id/iafs/:id/shortlist" => "iafs#shortlist", :as => "shortlist"
  get "company_informations/:company_information_id/iafs/:id/select_student" => "iafs#select_student", :as => "select_student"
  get "company_informations/:company_information_id/iafs/:id/unselect_student" => "iafs#unselect_student", :as => "unselect_student"
  get "students/:id/verify_confirm" => "students#verify_confirm", :as => "confirm_student"
  get "company_informations/:company_information_id/iafs/:id/freeze_shortlist" => "iafs#freeze_shortlist", :as => "freeze_shortlist"
 
resources :sessions
  resources :company_informations	do
  	resources :iafs
  end
end

FinalProject/src/company/app/models/verification.rb
class Verification < ActiveRecord::Base
	belongs_to :student
	has_attached_file :proof
	validates_attachment :proof,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

FinalProject/src/company/app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
	def index
		@student = Student.find(params[:student_id])
		@verifications=@student.verifications.all

	end	

	def show

    	@verification = Verification.find(params[:id])
  	end

	def new
		 @student = Student.find(params[:student_id])
		 @verification = @student.verifications.build
	end

  	def create
  		@student = Student.find(params[:student_id])
  		@verification = @student.verifications.build(verification_params)

  	
    if @verification.save
      flash[:success] = "The proof was added!"
      redirect_to student_verification_path(:id =>@verification)
    else
      render 'new'
    end
 	end

 	def destroy
    @verification = Verification.find(params[:id])
    @verification.destroy
 
    redirect_to student_verifications_path
  end

 	 private

 	 def verification_params
    	params.require(:verification).permit(:point, :proof, :mail_id, :student_id)
  	 end
end

FinalProject/src/company/app/helpers/verifications_helper.rb
module VerificationsHelper
end

FinalProject/src/company/app/views/verifications/index.html.erb
  <div id="menu">
    <ul>
      <li><%= link_to "Home", student_path(@student.id) %></li>
      <li><%= link_to "IAFS", student_all_iafs_path(@student.id) %></li>
      <li class="current_page_item"><a href="#">Resumes</a></li>
      <li><%= link_to "Profile", edit_student_path(@student.id) %></li>
      <li><%= link_to "Reviews", student_reviews_path(@student.id) %></li>
      <li class="last"><%= link_to "Logout", log_out_path %></li>
    </ul>
  </div>
  <div id="two-columns">
    <div id="column-list">
      <h2>Resume</h2>
      <ul class="list-style2">
        <li class="first"><%= link_to "One page technical (Resume_1)", @student.cv.url(:original, false) %></li><!-- 
        <li><%= link_to "Two page technical (Resume_1)", @student.cv.url(:original, false) %></li>
        <li><%= link_to "Three page technical (Resume_1)", @student.cv.url(:original, false) %></li>
        <li><%= link_to "One page non-technical (Resume_1)", @student.cv.url(:original, false) %></li>
        <li><%= link_to "Two page non-technical (Resume_1)", @student.cv.url(:original, false) %></li> -->
      </ul>
      <!-- <h2>SOP
        <% if current_student.admin %>
        <% else %>
        <%= link_to 'Upload SOP', upload_student_path(@student), class: 'btn btn-success float-R' %>
        <% end %>
      </h2>
      <ul class="list-style2 text-center">
        <li class="first"><%= link_to "SOP 1", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 2", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 3", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 4", @student.cv.url(:original, false) %></li>
        <li><%= link_to "SOP 5", @student.cv.url(:original, false) %></li>
      </ul> -->
    </div>
    <div id="column-details">
      <!-- For Student Side -->
      <h2>Resume_0 
        <% if current_student.admin %>
        <% else %>
        <%= link_to 'Edit', upload_student_path(@student), class: 'btn btn-file float-R' %>
        <%= link_to "140050007-0.pdf", @student.cv.url(:original, false), class: 'float-R' %>
        <% end %>
      </h2>
      <ul class="list-style1">
        <% @verifications.each do |verification| %>
        <li class="bottom row">
          <div class="col-xs-9">
            <h4><%= verification.point %></h4>
            <p><strong>File for Proof : </strong><%= link_to verification.proof_file_name, verification.proof.url(:original, false) %><!-- <a href="#"><%= verification.proof_file_name %></a> -->
            <% if current_student.admin %>
            <% else %>
            <%= link_to 'View Details', student_verification_path(:id =>verification), class: 'btn btn-info btn-sm margin-left-5' %></p>
            <%= link_to 'Remove Point', student_verification_path(:id =>verification), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </div>
          <div class="col-xs-3">Status : 
            <% if @student.verified %>
            <button class="btn btn-success">Validated</button>
            <% else %>
            <button class="btn btn-secondary">Pending</button>
            <% end %>
          </div>
        </li>
        <% end %>
        
        <!-- <li class="bottom row">
          <div class="col-xs-9">
            <h4>Short listed for KVPY Fellowship Award conducted by IISC, Bangalore</h4>
            <p><strong>File for Proof : </strong><a href="#">someOtherFile.jpg</a></p>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-success">Validated</button></div>
        </li>
        <li class="bottom row">
          <div class="col-xs-9">
            <h4>Secured 98/100 in the finals of All India Open Mathematics Scholarship Examination (AIOMSE) conducted by Institute for Promotion of Mathematics (IPM)</h4>
            <p><strong>File for Proof : </strong><a href="#">someAnotherFile.jpg</a><button class="btn btn-info btn-sm margin-left-5">Edit</button></p>
            <button class="btn btn-danger">Remove Point</button>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-danger">Invalidated</button><br><strong>Comment : </strong>Proof shows 99/100, Please update the point</div>
        </li> -->
        <li class="row">
          <h2>
            <% if current_student.admin %>
            <%= link_to 'Verify', verify_student_path(@student), class: "btn btn-success btn-lg margin-left-5" %>
            <% else %>
            <%= link_to 'Add a Point', new_student_verification_path, class: "btn btn-primary btn-lg margin-left-5" %>
            <% end %>
          </h2>
        </li>
      </ul><!-- 
      <% if current_student.admin %>
      <h4 class="text-right"><strong>Mail To : </strong><a href="#">Neeladrishekhar Kanjilal</a></h4>
      <% end %> -->
      <!-- End For Student Side -->
      <!-- For Verifier Side -->
      <!-- <h2>Resume_0 <a href="#" class="float-R">140050007-0.pdf</a></h2>
      <ul class="list-style1">
        <li class="first row">
          <div class="col-xs-9">
            <h4>City Topper in SSC Maharashtra Secondary State Board Examination</h4>
            <p><strong>File for Proof : </strong><a href="#">someFile.jpg</a></p>
            <div class="btn-group float-R" role="group" aria-label="..."><button class="btn btn-success">Validate</button><button class="btn btn-danger">Invalidate</button></div>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-secondary">Pending</button></div>
        </li>
        <li class="row">
          <div class="col-xs-9">
            <h4>Short listed for KVPY Fellowship Award conducted by IISC, Bangalore</h4>
            <p><strong>File for Proof : </strong><a href="#">someOtherFile.jpg</a></p>
            <div class="btn-group float-R" role="group" aria-label="..."><button class="btn btn-success">Validate</button><button class="btn btn-danger">Invalidate</button></div>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-success">Validated</button></div>
        </li>
        <li class="row">
          <div class="col-xs-9">
            <h4>Secured 98/100 in the finals of All India Open Mathematics Scholarship Examination (AIOMSE) conducted by Institute for Promotion of Mathematics (IPM)</h4>
            <p><strong>File for Proof : </strong><a href="#">someAnotherFile.jpg</a></p>
            <div class="btn-group float-R" role="group" aria-label="..."><button class="btn btn-success">Validate</button><button class="btn btn-danger">Invalidate</button></div>
          </div>
          <div class="col-xs-3">Status : <button class="btn btn-danger">Invalidated</button><br><strong>Comment : </strong>Proof shows 99/100, Please update the point</div>
        </li>
      </ul>
       -->
    </div>
  </div>

FinalProject/src/company/app/views/verifications/new.html.erb
<div id="welcome">
<%= form_for :verification, url: student_verifications_path do |f| %>
  <p>
    <%= f.label "Resume Point" %><br>
    <%= f.text_field :point, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label "proof" %><br>
    <%= f.file_field :proof, class: 'form-control' %>
  </p>

    <p>
    <%= f.label "mail_id" %><br>
    <%= f.text_area :mail_id, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.submit %>
    <%= link_to "Back", student_verifications_path(@student), class: 'btn btn-primary float-R' %>
  </p>
<% end %>
</div>

FinalProject/src/company/app/views/verifications/show.html.erb
<div id="welcome">
<p>
  
    <tr>
     <td><%= @verification.student_id %> </td>	
      <td><%= @verification.point %></td>
      <td> student_id</td>
      <td><%= @verification.student_id %></td>
      <td><%= link_to "Download", @verification.proof.url(:original, false) %></td>
      <td><%= @verification.mail_id %></td>
    </tr>
 </p>   

<p><%= link_to 'Add another', new_student_verification_path %> </p>
<p><%= link_to 'Back', student_verifications_path %>  </p>  

</div>